config/routes.rb
Blog::Application.routes.draw do

  resources :assets

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :posts

  resources :categories

  resources :posts
    match '/feed' => 'posts#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }

  root :to => 'posts#index'

end

app/views/admin/index.html.erb
<% content_for :title, "Admin" %>

<h1>Super Secret Administration Panel</h1>
<div id="admin">

<div class="float-right"><%= link_to 'New post', 'posts/new', :class => 'button icon add'  %><%= link_to 'New user', 'users/new', :class => 'button icon user'  %></div>

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#posts" data-toggle="tab">Posts</a></li>
    <li><a href="#users" data-toggle="tab">Users</a></li>
  </ul>
  <div class="tab-content">

    <div class="tab-pane active" id="posts">
      <table id="posts">
        <tr>
          <th class="title">Title</th>
          <th>Author</th>
          <th>Published</th>
          <th>Updated</th>
        </tr>

        <% @posts.each do |post| %>
          <tr>
            <td> <%= post.title %> </td>
            <td> <%= User.find_by_id(post.user_id).username %> </td>
            <td>
            <% if post.published %>
              <%= post.published_at.strftime("%d/%m/%y") %>
            <% else %>
              no yet
            <% end %>
            </td>
            <td> <%= post.updated_at.strftime("%d/%m/%y") %> </td>
            <td><%= search_button_link_to 'Show', post %></td>
            <td><%= edit_button_link_to 'Edit', edit_post_path(post) %></td>
            <td><%= trash_button_link_to 'Destroy', post, :method => :delete, data: { confirm: 'Are you sure?' }  %></td>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="tab-pane" id="users">
      <table id="users">
        <tr>
          <th class="username">Username</th>
          <th class="email">E-mail</th>
          <th class="first">First</th>
          <th class="second">Second</th>
        </tr>

        <% @users.each do |user| %>
          <tr>
            <td> <%= user.username %> </td>
            <td> <%= user.email %> </td>
            <td> <%= user.first_name %> </td>
            <td> <%= user.second_name %> </td>
            <td><%= search_button_link_to 'Show', user %></td>
            <td><%= edit_button_link_to 'Edit', edit_user_path(user) %></td>
            <td><%= trash_button_link_to 'Destroy', user, :method => :delete, data: { confirm: 'Are you sure?' }  %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
</div>