config/routes.rb
Blog::Application.routes.draw do

  resources :assets

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :posts

  resources :categories

  resources :posts
    match '/feed' => 'posts#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }

  root :to => 'posts#index'

end

app/models/user.rb
require 'digest/sha2'
require 'rdiscount'

class User < ActiveRecord::Base
  attr_accessible :first_name, :hashed_password, :salt, :second_name, :username, :password, :password_confirmation, :email, :bio, :bio_md
  has_many :posts, :dependent => :destroy

  validates :username, :presence => true, :uniqueness => true
  validates :password, :confirmation => true, :length => {:within => 8..40}, :if  => :password_changed?
  attr_accessor :password_confirmation
  attr_reader   :password

  validates :email, :email => {:strict_mode => true}, :uniqueness => true
  
  validate  :password_must_be_present

  after_destroy :ensure_an_admin_remains

  before_create :bio_markdown_to_html
  before_save :bio_markdown_to_html

  # change urls
  def to_param
    username
  end

  def User.authenticate(username, password)
    if user = find_by_username(username)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end
  
  # 'password' is a virtual attribute
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  private

    def password_must_be_present
      errors.add(:password, "missing password") unless hashed_password.present?
    end
  
    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end

    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end

    def bio_markdown_to_html
      if self.bio_md
        markdown = RDiscount.new(self.bio_md)
        self.bio = markdown.to_html 
      end
    end

    def password_changed?
      !@password.blank? or hashed_password.blank?
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:username)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_username!(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find_by_username!(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.username} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find_by_username!(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: "User #{@user.username} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find_by_username!(params[:id])
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @user, :html => { :class => "form-horizontal"} do |f| %>
  <%= f.input :username, :placeholder => 'username', :required => false %>
  <%= f.input :email, :placeholder => 'E-mail' %>
  <%= f.input :first_name, :placeholder => 'First name' %>
  <%= f.input :second_name, :placeholder => 'Second name' %>
  <% if current_url == new_user_url %>
     <%= f.input :password, :placeholder => 'password' %>
    <%= f.input :password_confirmation, :placeholder => 'password' %>
  <% else %>
    <%= f.input :password, :placeholder => 'Leave blank to keep the current', :label => "<strong>New</strong> password" %>
    <%= f.input :password_confirmation, :placeholder => 'Leave blank to keep the current', :label => "Confirmation" %>
  <% end %>
  <%= f.input :bio_md, :placeholder => 'Your biography in *markdown* sintax', :label => 'Biography' %>
  <div class="button-submit-centered">
    <%= f.button :submit, :class => "button primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="user">
  
  <div id="avatar">
    <%= gravatar_image_tag(user.email, :alt => user.username) %>
  </div>

  <div id="info">
    <div id="username"><strong><%= link_to user.username, user %></strong></div>
    <div id="name"><%= user.first_name %> <%= user.second_name %></div>
    <div id="email"><%= mail_to user.email, nil, :replace_at => "_at_", :replace_dot => "_dot_", :class => "email" %></div>
    <div id="bio"><strong>About</strong>: <%= raw user.bio %></div>
  </div>

  <% if session[:user_id] %>
    <%= link_to 'Edit', edit_user_path(user), :class => 'button icon edit' %>
  <% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<div id="user">
<%= render 'form' %>
</div>

app/views/users/index.html.erb
<%= content_for :title, "Users" %>
<h1>All users</h1>
<%= render @users %>

app/views/users/new.html.erb
<h1>New user</h1>

<div id="user">
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<%=h content_for :title, @user.username %>

<div id="user">
<%= render @user %>
</div>