config/routes.rb
Blog::Application.routes.draw do

  resources :assets

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :posts

  resources :categories

  resources :posts
    match '/feed' => 'posts#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }

  root :to => 'posts#index'

end

app/models/post.rb
require 'rdiscount'

class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :category_list, :content_md, :published, :published_at, :assets_attributes
  belongs_to :user

  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets, :allow_destroy => true

  before_create :create_slug
  before_save :create_slug

  before_create :content_markdown_to_html
  before_save :content_markdown_to_html

  before_create :insert_publish_date
  before_save :insert_publish_date

  # Alias for acts_as_taggable_on :tags
  # acts_as_taggable
  acts_as_taggable_on :categories

  validates :title, :presence => true, :uniqueness => true
  validates :content_md, :presence => true

  
  def to_param
    slug
  end

  private
   
    def create_slug
      if self.title
        self.slug = self.title.parameterize
      end
    end

    def content_markdown_to_html
      if self.content_md
        markdown = RDiscount.new(self.content_md)
        self.content = markdown.to_html
      end 
    end

    def insert_publish_date
      if self.published && !self.published_at
        tmp = Post.find_by_id(self.id)
        if !tmp || !tmp.published_at
          self.published_at = DateTime.current
        end
      end 
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authorize, :only => [:index, :show, :feed]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(:published => true).order("published_at DESC").paginate(:page => params[:page], :order=>'created_at desc',
      :per_page => 5)

    if request.xhr?
      sleep(2) # UX tip: make request a little bit slower to see loader :-)
      render :partial => @posts
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @posts }
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_slug!(params[:id])

    # not show drafts to visitors
    if !@post.published && !session[:user_id]
      not_found
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    2.times { @post.assets.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find_by_slug!(params[:id])
    2.times { @post.assets.build }
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to edit_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render json: edit_post_path(@post), status: :created, location: @post }
        format.js   { render :nothing => true }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    #@post = Post.find(params[:id])
    @post = Post.find_by_slug!(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to edit_post_url(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
        format.js   { render :nothing => true }
      else
        format.html { render action: "edit" }
        format.json { render json: edit_post_url(@post).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    #@post = Post.find(params[:id])
    @post = Post.find_by_slug!(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def feed
    # this will be the name of the feed displayed on the feed reader
    @title = "Life of a Dev"

    # the news items
    @posts = Post.find_all_by_published(true)
    if @posts
      @posts = @posts.sort_by(&:published_at).reverse!
    end

    # this will be our Feed's update timestamp
    @updated = @posts.first.published_at unless @posts.empty?

    respond_to do |format|
      format.atom { render :layout => false }

      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<script type="text/javascript">
  jQuery(document).ready(function($){
    $('.editor').MarkdownEditor();
  });

  // intercept CMD+S
  var lastKey;
  $(document).keydown(function(event){
    if ((lastKey == 91) && event.keyCode == 83) {
      $("#save-button").trigger('click');
      return false;
    }
    lastKey = (event.keyCode == 91) ? 91 : 0;
  });
</script>

<% if @post.errors.any? %>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @post, :html => { :class => "form-horizontal", :id => "edit-post-form", :multipart => true} do |f| %>
  <%= f.input :title, :placeholder => 'Title', :required => false %>

  <div class="editor">
    <div class="controls clear-block hide-if-no-js button-group">
        <a class="control c-bold button" accesskey="b"><strong>B</strong></a>
        <a class="control c-italic button" accesskey="i"><em>I</em></a>
        <a class="control c-link button" accesskey="a">Link</a>
        <a class="control c-image button" accesskey="m">I<span>m</span>age</a>
        <a class="control c-quote button" accesskey="q"><span>Q</span>uote</a>
        <a class="control c-code button" accesskey="c"><span>C</span>ode</a>
      </div>
    <%= f.input :content_md, :placeholder => 'Post in *markdown* syntax post here', :html => { :class => "post_content"}, :label => 'Content', :required => false %>
  </div>

  <%= f.input :category_list, :placeholder => 'Categories separated by commas' %>
  <%= f.input :published, :label => "Publish?", :inline_label => "If unchecked this post will be saved as draft" %>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => session[:user_id] } %>
  
  <div id="paperclip">
    <div class="new-paperclip">
      <%= f.fields_for :assets do |asset| %>
        <% if asset.object.new_record? %>
          <%= asset.file_field :image %><br>
        <% end %>
      <% end %>
    </div>
    <% if @post && post_has_assets(@post.id) %>
      <div class="old-paperclip">
        <table>
          <tr>
            <th><strong>Thumb</strong></th>
            <th><strong>Link</strong></th>
            <th><strong>Delete?</strong></th>
          </tr>
          <%= f.fields_for :assets do |image_fields| %>
            <tr>
              <% unless image_fields.object.new_record? %>
                <td><%= link_to( image_tag(image_fields.object.image.url(:thumb)), image_fields.object.image.url(:original) ) %></td>
                <td><%= image_fields.object.image.url(:large) %></td>
                <td style="text-align:center"><%= image_fields.check_box :_destroy %></td>
              <% end %>
            </tr> 
          <% end %>
        </table>
      </div>
    <% end %>
  </div>

  <% #f.button :submit, 'Save', :class => "button primary big", :id => 'save-button', :remote => true %>
  <%= pill_primary__big_button_submit_tag '⌘ + S', :id => 'save-button' %>
<% end %>

app/views/posts/_post.html.erb
<div id="post">
    
  <div id="title">
    <%= link_to(post.title, post) %>

    <% if session[:user_id] %>
      <span style="margin-left=20px;float:right;"><%= link_to 'Edit', edit_post_path(post), :class => 'button icon edit' %></span>
    <% end %>
  </div>
  
  <div id="content"><%= raw post.content %></div>

  <div class="tweet-button">
    <%= button_link_to 'Tweet', 'https://twitter.com/share?text=' + post.title + '&url='+"#{request.protocol}#{request.host_with_port}/#{post.slug}"+'&via=LifeofaDev',
        :class => 'button icon tweet', :target => "_blank" %>
  </div>

  <div id="info">
    Author:
    <% @author = User.find_by_id(post.user_id) %>
    <%= link_to( @author.username, @author ) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <% if post.published %>
      <span class="label-calendar">&nbsp; &nbsp; &nbsp;<%=  post.published_at.strftime("%d %b %Y")  %></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <% end %>

    <% if request.env['PATH_INFO'] != post_path(post) %>
      <span class="label-comments">&nbsp; &nbsp; &nbsp;<%= link_to 'Comments', post_url(post) + "#disqus_thread"  %></span>
    <% end %>&nbsp;&nbsp;&nbsp;

    <% categories = post.category_list %>
    <% if !categories.empty? %>
      <span class="label-categories">&nbsp; &nbsp; &nbsp;  
        <% categories.each_with_index do |category, i| %>
          <%=  link_to category, category_url(category) %>
          <% if i != categories.length-1 %>
            <%= '|' %>
          <% end %>
        <% end %>
      </span>
    <% end %>
  </div>
  

  
  <% if current_url == post_url(post) %>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
          /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
          var disqus_shortname = 'lifeofadev'; // required: replace example with your forum shortname

          /* * * DON'T EDIT BELOW THIS LINE * * */
          (function() {
              var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
              dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
              (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>  
  <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Edit post" %>
<h1>Edit post</h1>

<div id="post">
  <div class="float-right" style="margin-top:12px;margin-right:23px">
    <%= link_to 'View', @post, :class => 'button icon search', :target => '_blank'  %>
  </div>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Life of a Dev" %>

<div id="results">
<%= render :partial => 'post', :collection => @posts %>
</div>

<br>
<%= will_paginate @orders %>
<%= pageless(@posts.total_pages, posts_path) %>

app/views/posts/new.html.erb
<% content_for :title, "New Post" %>
<h1>New Post</h1>

<div id="post">
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<% content_for :title, @post.title %>

<%= render @post %>